import type { Metadata } from "next";

import dayjs from "dayjs";
import timezone from "dayjs/plugin/timezone";

import JotaiProvider from "./JotaiProvider";
import "./globals.scss";

interface Props {
  children: React.ReactNode;
}

dayjs.extend(timezone);
dayjs.tz.setDefault("Asia/Seoul");

const RootLayout = ({ children }: Props) => {
  return (
    <html lang="ko">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css"
        />
      </head>
      <body>
        <JotaiProvider>{children}</JotaiProvider>
      </body>
    </html>
  );
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default RootLayout;
